spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: SARTHAK
    password: Sinha@9818
    url: jdbc:mysql://localhost:3306/microservices
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
 
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: USER-SERVICE      
  config:
    import: optional:configserver:http://localhost:8084
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-25271320.okta.com/oauth2/default
      client:
        registration: 
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials 
            scope: internal
            client-id: 0oaexjosqkFXOjwVG5d7
            client-secret: fnzjqT1CYJfWM2uwdzAoIKcgwWV24R5lsfzOjuAvU-t4tLJHeU0UTjxbL7S8R11w
    
        provider:
          okta:
            issuer-uri: https://dev-25271320.okta.com/oauth2/default
            
    
    
    
resilience4j:
  circuitbreaker:
    instances:
     Rating-Hotel-Breaker: 
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 10
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 6s
       permitted-number-of-calls-in-half-open-state: 5
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED
     
     Rating-Hotel-Breaker2: 
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 10
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 6s
       permitted-number-of-calls-in-half-open-state: 5
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED  
       
  ratelimiter:
    instances:
      RateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
       
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
      
okta:
  oauth2:
    issuer: https://dev-25271320.okta.com/oauth2/default
    audience: api://default


    
    
    
    