spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
  application:
    name: RATING-SERVICE
  config:
        import: optional:configserver:http://localhost:8084



#eureka:
#  instance:
#    hostname: localhost   
#  client:
#    service-url:
#      defaultZone: http://localhost:1234/eureka
#      
      
server:
  port: 9082
  
  

okta:
  oauth2:
    issuer: https://dev-25271320.okta.com/oauth2/default 
    audience: api://default
    
    
    
    
    
    